module.exports={
    getdata(){
        let a={
            list:["美妆个护", "家居生活", "生活家电", "男装", "女装", "儿童", "鞋履", "箱包", "内衣", "配饰"],
            goodsList:[
                {
                    title01:"美妆个护",
                    title02:"美妆个护",
                    section02:[
                        {src:"assets/mzgh01.jpg",word:"美妆"},
                        {src:"assets/mzgh02.jpg",word:"洗发护发"},
                        {src:"assets/mzgh03.jpg",word:"口腔护理"},
                        {src:"assets/mzgh04.jpg",word:"身体护理"},
                    ]
                },
                {
                    title01:"家居生活",
                    title02:"家居生活",
                    section02:[
                        {src:"assets/jjsh01.jpg",word:"居家日用"},
                        {src:"assets/jjsh02.jpg",word:"厨房餐饮"},
                    ]
                },
                {
                    title01:"生活家电",
                    title02:"生活家电",
                    section02:[
                        {src:"assets/shjd01.jpg",word:"家用电器"},
                        {src:"assets/shjd02.jpg",word:"个护电器"},
                    ]
                },
                {
                    topImage:["assets/nztop.jpg"],
                    title01:"上装",
                    section01:[
                        {src:"assets/nzs01.jpg",word:"卫衣"},
                        {src:"assets/nzs02.jpg",word:"毛衣"},
                        {src:"assets/nzs03.jpg",word:"夹克"},
                        {src:"assets/nzs04.jpg",word:"风衣"},
                        {src:"assets/nzs05.jpg",word:"大衣"},
                        {src:"assets/nzs06.jpg",word:"西服"},
                        {src:"assets/nzs07.jpg",word:"羽绒服"},
                        {src:"assets/nzs08.jpg",word:"长袖衬衫"},
                        {src:"assets/nzs09.jpg",word:"长袖T恤"},
                        {src:"assets/nzs10.jpg",word:"短袖T恤"},
                        {src:"assets/nzs11.jpg",word:"短袖衬衫"}
                    ],
                    title02:"下装",
                    section02:[
                        {src:"assets/nzx01.jpg",word:"牛仔长裤"},
                        {src:"assets/nzx02.jpg",word:"休闲长裤"},
                        {src:"assets/nzx03.jpg",word:"针织休闲长裤"},
                        {src:"assets/nzx04.jpg",word:"西裤"},
                        {src:"assets/nzx05.jpg",word:"牛仔中短裤"},
                        {src:"assets/nzx06.jpg",word:"休闲中短裤"},
                        {src:"assets/nzx07.jpg",word:"针织中短裤"}
                        ]
                },
                {
                    topImage:["assets/wnztop.jpg"],
                    title01:"上装",
                    section01:[
                        {src:"assets/wnzs01.jpg",word:"卫衣"},
                        {src:"assets/wnzs02.jpg",word:"毛衣"},
                        {src:"assets/wnzs03.jpg",word:"长袖衬衫"},
                        {src:"assets/wnzs04.jpg",word:"夹克"},
                        {src:"assets/wnzs05.jpg",word:"风衣"},
                        {src:"assets/wnzs06.jpg",word:"大衣"},
                        {src:"assets/wnzs07.jpg",word:"棉服"},
                        {src:"assets/wnzs08.jpg",word:"羽绒服"},
                        {src:"assets/wnzs09.jpg",word:"短袖T恤"},
                        {src:"assets/wnzs10.jpg",word:"短袖衬衫"}
                    ],
                    title02:"下装",
                    section02:[
                        {src:"assets/wnzx01.jpg",word:"休闲长裤"},
                        {src:"assets/wnzx02.jpg",word:"针织裤"},
                        {src:"assets/wnzx03.jpg",word:"牛仔中短裤"},
                        {src:"assets/wnzx04.jpg",word:"休闲中短裤"}
                    ],
                    title03:"裙装",
                    section03:[
                        {src:"assets/wnzq01.jpg",word:"连衣裙"},
                        {src:"assets/wnzq02.jpg",word:"半身裙"}
                    ]
                },
                {
                    title01:"男童",
                    section01:[
                        {src:"assets/etn01.jpg",word:"衬衫"},
                        {src:"assets/etn02.jpg",word:"卫衣"},
                        {src:"assets/etn03.jpg",word:"外套"},
                        {src:"assets/etn04.jpg",word:"长裤"},
                        {src:"assets/etn05.jpg",word:"鞋包配"},
                        {src:"assets/etn06.jpg",word:"T恤"}
                    ],
                    title02:"女童",
                    section02:[
                        {src:"assets/etwn01.jpg",word:"衬衫"},
                        {src:"assets/etwn02.jpg",word:"卫衣"},
                        {src:"assets/etwn03.jpg",word:"外套"},
                        {src:"assets/etwn04.jpg",word:"长裤"},
                        {src:"assets/etwn05.jpg",word:"鞋包配"},
                        {src:"assets/etwn06.jpg",word:"裙装"},
                        {src:"assets/etwn07.jpg",word:"T恤"}
                    ],
                    title03:"婴幼童",
                    section03:[
                        {src:"assets/etyyt02.jpg",word:"上装"},
                        {src:"assets/etyyt01.jpg",word:"下装"}
                    ]
                },
                {
                    title01:"男鞋",
                    section01:[
                        {src:"assets/etn01.jpg",word:"休闲鞋"},
                        {src:"assets/etn02.jpg",word:"运动鞋"},
                        {src:"assets/etn03.jpg",word:"商务鞋"},
                        {src:"assets/etn04.jpg",word:"帆布鞋"},
                        {src:"assets/etn05.jpg",word:"凉/拖鞋"}
                    ],
                    title02:"女鞋",
                    section02:[
                        {src:"assets/etwn01.jpg",word:"休闲鞋"},
                        {src:"assets/etwn02.jpg",word:"运动鞋"},
                        {src:"assets/etwn03.jpg",word:"商务鞋"},
                        {src:"assets/etwn04.jpg",word:"帆布鞋"},
                        {src:"assets/etwn05.jpg",word:"靴子"},
                        {src:"assets/etwn06.jpg",word:"凉/拖鞋"}
                    ]
                },
                {
                    topImage:["assets/xbtop.jpg"],
                    title01:"品质男包",
                    section01:[
                        {src:"assets/xbn01.jpg",word:"钱包/手拿"},
                        {src:"assets/xbn02.jpg",word:"胸包"},
                        {src:"assets/xbn03.jpg",word:"双肩包"}
                    ],
                    title02:"潮流女包",
                    section02:[
                        {src:"assets/xbwn01.jpg",word:"单肩包"},
                        {src:"assets/xbwn02.jpg",word:"双肩包"},
                        {src:"assets/xbwn03.jpg",word:"斜挎包"},
                        {src:"assets/xbwn04.jpg",word:"钱包/手拿"},
                        {src:"assets/xbwn05.jpg",word:"手提包"},
                        {src:"assets/xbwn06.jpg",word:"胸包/腰包"}
                    ]
                },
                {
                    title01:"男内衣",
                    section01:[
                        {src:"assets/nyn01.jpg",word:"内衣下装"},
                        {src:"assets/nyn02.jpg",word:"袜子"}
                    ],
                    title02:"女内衣",
                    section02:[
                        {src:"assets/nywn01.jpg",word:"家居服"},
                        {src:"assets/nywn02.jpg",word:"内衣套装"},
                        {src:"assets/nywn03.jpg",word:"袜子"}
                    ],
                    title03:"内衣"
                },
                {
                    title01:"配饰",
                    section01:[
                        {src:"assets/ps01.jpg",word:"帽子"},
                        {src:"assets/ps02.jpg",word:"围巾/丝巾"},
                        {src:"assets/ps03.jpg",word:"腰带/皮带"},
                        {src:"assets/ps04.jpg",word:"其他配饰"},
                        {src:"assets/ps05.jpg",word:"腕表"}
                    ]
                }
            ]
        }
        return a
    }

}