module.exports={
	getdata(){
		let a={
			"src":[
				"assets/banner01.jpg",
				"assets/banner02.jpg",
				"assets/banner03.jpg",
				"assets/banner04.jpg",
				"assets/banner05.jpg"
				],
			"nav":[
				"assets/homeNav00.jpg",
				"assets/homeNav01.jpg",
				"assets/homeNav02.jpg",
				"assets/homeNav03.jpg",
				"assets/homeNav04.jpg",
				],
			"discount":[
				"assets/homediscount01.jpg",
				"assets/homediscount02.jpg",
				"assets/homediscount03.jpg",
				"assets/homediscount04.jpg",
				"assets/homediscount05.jpg",
				"assets/homediscount06.jpg",
			],
			"hotbrands":[
				"assets/hotbrands02.jpg",
				"assets/hotbrands03.jpg",
				"assets/hotbrands04.jpg",
				"assets/hotbrands05.jpg",
				"assets/hotbrands06.jpg",
				"assets/hotbrands07.jpg",
			],
			"hotitems":[
				"assets/hotitems02.jpg",
				"assets/hotitems03.jpg",
				"assets/hotitems04.jpg",
				"assets/hotitems05.jpg",
				"assets/hotitems06.jpg",
				"assets/hotitems07.jpg",
			],
			"homeshop":[
				"assets/shop2.gif",
				"assets/shop1.jpg",
			]
		};
		return a
	}
}